### ISSUE TITLE
Delayed Reading In Arduino Sleep Mode

### ISSUE THREAD

**Issue by Raphael909** [MartinL1/BMP280_DEV#10]
Hello Martin, 
It may turn out not to be a bug or issue but I am wondering if you have seen any issue when waking up arduino from sleep mode and performing a reading.
The way I have set up is:
1. Wake up Arduino every 2 minutes or if there is an external Interrupt.
2. Perform reading.
3. BMP280 Running in NORMAL_MODE
4. Filter setup for Operation `Interior Navigation` with 500MS standby.

Observation:
1. Delayed 1st reading sometimes take more than 10 mins(worst was 30 mins) and then subsequent readings are bit faster.
2. No values when Sensor is in Sleep_mode with deep sleep mode in place. Made sure to do force measurement on wake.

If it helps... I also experimented with Adafruit Library and I did not see this anomaly. Wondering if this has to do with making it non-blocking i.e check for status reg etc. 

Also, it will be very helpful to folks if you could throw in an example of: performing Temperature Readings with Arduino deep sleep mode.
 
Thank you for any help and also for a wonderful Library!

**Comment by MartinL1** [comment]
Hi Raphael909,

Thank you for your kind words regarding BMP280_DEV library.

The last time I looked, the Adafruit BMP280 library used blocking code in FORCED mode and not the periodic NORMAL measurement mode when reading the device. 

There's a hardware design issue with the BMP280, in that it uses a "measurement" bit that indicates when a measurement is being made, however this doesn't actually indicate whether results are ready or if the device is simply in idle in sleep mode. Therefore in NORMAL mode it's necessary to regularly poll the device to dectect edges of the measurement bit in software. This design pattern though doesn't fit if you're putting the microcontroller to sleep. In this instance, it's better to use FORCED measurement mode and block within a while{} loop containing the "getMeasurements()" function until the measurement has been read before going back to sleep.

Later Bosch barometers, such as the BMP3XX series, uses a "ready" bit that flags when the results are actually ready to be read. This subtle but important change resolves this issue and makes the software design much simpler, (see BMP388_DEV library).

Kind regards,
MartinL1
