### ISSUE TITLE
no matching function for call to 'BMP280_DEV::BMP280_DEV(int, int)'

### ISSUE THREAD

**Issue by wadoadi** [MartinL1/BMP280_DEV#12]
hi 
I'm using the Arduino IDE and an ESP32 board connected to DY-91 which has an BMP280 on board. I'm using the default SDL and SDA for the ESP 21 and 22.

however when using you example file i get the following error:
no matching function for call to 'BMP280_DEV::BMP280_DEV(int, int)'

**Comment by MartinL1** [comment]
Hi wadoladi,

The BMP280_DEV constructor with two integer parameters is designed for use with the ESP8266. A microcontroller that doesn't have a native hardware I2C port and therefore requires the SCL and SDA lines to be specified.

To use the ESP32 with the BMP280_DEV library and I2C simply call the constructor with the line:
```
BMP280_DEV bmp280;
```
The default SCL (GPIO22) and SDA (GPIO21) pins will be automatically selected.

Kind regards,
MartinL1
