### ISSUE TITLE
 All the same problems with BMP280

### ISSUE THREAD

**Issue by Gennadiy1990** [MartinL1/BMP280_DEV#14]
Good day!
I did not notice your answer, for some unknown reason it ended up in spam. Sorry!
I want to say that the problem remains. The levels are matched through 
a proven circuit on two FETs. There was no such problem with BMP180 when
 I used it earlier. This cannot be the reason. I got the original sensor
 from DIGIKEY. The problem has changed somewhat. But every time the power
 is turned on, several measurements are equal to 0. The number of incorrect
 results depends on oversampling. There are more for the X4 than for the X1. 
I checked all the settings in your library modes according to the 
manufacturer's documentation. Everything is correct. Below are two 
sketches and results. Please review.  I just changed the address 
of the chip in your library, made the main one with the value of the
 alternative . One gets the impression that the sensor, after starting
 for several seconds, is busy with something unclear whether it is being 
 calibrated, or simply stopped. I have read all the documentation for the sensor.
 Found nothing. There is a library from BOSCH, but it is written in C and is large 
 for 328p.   
I also want to draw your attention to the fact that in the case of zeroing the 
variables at the beginning of each LOOP (), the results are always alternated 
with a value equal to 0 (SKETCH1, test 1).
Thanks!

Arduino IDE v1.8.2

// SKETCH1
#include <BMP280_DEV.h>
#include <Wire.h>
#define PIN_ZUMMER     A1

BMP280_DEV bmp280;

//see test2-floats before setup()
float  temperature = 0;          
float  pressure = 0;          
float  altitude = 0;         

void setup()
{
  pinMode(PIN_ZUMMER, OUTPUT);

  Serial.begin(9600);
  Serial.println( "Start");

  //if (bmp280.begin(NORMAL_MODE, OVERSAMPLING_X4, OVERSAMPLING_X1, IIR_FILTER_OFF, TIME_STANDBY_05MS) == 0)
  if (bmp280.begin(NORMAL_MODE, OVERSAMPLING_X1, OVERSAMPLING_X1, IIR_FILTER_OFF, TIME_STANDBY_05MS) == 0)
  {
    Serial.println( "************* BMP Error ***************");
  }
  delay(100);
  Serial.println( "LOOP");
}

void loop()
{
/* see test1-floats in head of loop() 
float  temperature = 0;          
float  pressure = 0;          
float  altitude = 0;          
*/
  bmp280.getMeasurements(temperature, pressure, altitude);
  Serial.print( "  pressure= ");  Serial.println( pressure , 2);

  if ( (pressure < 300) || (pressure > 1100))
  {
    digitalWrite(PIN_ZUMMER, HIGH);
    delay(100);
    digitalWrite(PIN_ZUMMER, LOW);
  }

}//END LOOP

TESTS:

 test 1
  for define OVERSAMPLING_X1
  float  temperature=0;            
  float  pressure=0;            
  float  altitude=0;            
  in head of loop() result is (NO power off):

  Start
  LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.82
  pressure= 0.00
  pressure= 1009.78
  pressure= 0.00
  pressure= 1009.79
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.78
  pressure= 0.00
  pressure= 1009.79
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.76
  pressure= 0.00
  pressure= 1009.73
  pressure= 0.00
  pressure= 1009.79
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.74
  pressure= 0.00
  pressure= 1009.72
  pressure= 0.00
  pressure= 1009.76
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.76
  pressure= 0.00
  pressure= 1009.82
  pressure= 0.00
  pressure= 1009.76
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.73
  pressure= 0.00
  pressure= 1009.72
  pressure= 0.00
  .
  .
  and etc.
 ****************************************************
  
  test 2 for define OVERSAMPLING_X1
  float  temperature=0;            
  float  pressure=0;            
  float  altitude=0;            
  before setup() result is( power on/off):
  //power on
     Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.94
  pressure= 1009.94
  pressure= 1009.94
  pressure= 1009.94
  pressure= 1010.03
  pressure= 1009.98
  //short power off/on
Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1010.02
  pressure= 1010.02
  pressure= 1010.02
  pressure= 1010.02
   //short power off/on
Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
   //short power off/on
  Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
  pressure= 1009.95
  
  **************************
  
  test 2 for define OVERSAMPLING_X4
  float  temperature=0;            // Create the temperature, pressure and altitude variables
  float  pressure=0;            // Create the temperature, pressure and altitude variables
  float  altitude=0;            // Create the temperature, pressure and altitude =vari* 
  before setup() result is( power on/off):
  //power on
 Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.44
  pressure= 1009.44
  pressure= 1009.44
  pressure= 1009.44
  pressure= 1009.44
  pressure= 1009.43
  
   //short power off/on
  
Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.40
  pressure= 1009.40
  pressure= 1009.40
  pressure= 1009.40
  pressure= 1009.40
      
   //short power off/on
  Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.45
  pressure= 1009.45
  pressure= 1009.45
     //short power off/on
  
  Start
LOOP
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 0.00
  pressure= 1009.45
  pressure= 1009.45
  pressure= 1009.45
  pressure= 1009.45

  
  
  
 //SKETCH2
#include <BMP280_DEV.h>
#include <Wire.h>
#define PIN_ZUMMER     A1

BMP280_DEV bmp280;
float  temperature=0;            
float  pressure=0;            
float  altitude=0;            

void setup()
{
  pinMode(PIN_ZUMMER, OUTPUT);
 
  Serial.begin(9600);
  Serial.println( "Start");

//if (bmp280.begin(NORMAL_MODE, OVERSAMPLING_X4, OVERSAMPLING_X1, IIR_FILTER_OFF, TIME_STANDBY_05MS) == 0)
if (bmp280.begin(NORMAL_MODE, OVERSAMPLING_X1, OVERSAMPLING_X1, IIR_FILTER_OFF, TIME_STANDBY_05MS) == 0)
  {
    Serial.println( "************* BMP Error ***************");
  }
  for (int i = 0; i < 15; i++)
      {
  bmp280.getMeasurements(temperature, pressure, altitude); 
  Serial.print(" pressure= ");  Serial.print( pressure , 2); 
  Serial.print(" temperature= " ); Serial.print (temperature,2);
  Serial.print(" altitude= ");Serial.println(altitude,2);                   
      }
  
   Serial.println( "LOOP");
}

void loop()
{
  bmp280.getMeasurements(temperature, pressure, altitude);
  Serial.print(" pressure= ");  Serial.print( pressure , 2); 
  Serial.print(" temperature= " ); Serial.print (temperature,2);
  Serial.print(" altitude= ");Serial.println(altitude,2);
     

  if ( (pressure < 300) || (pressure > 1100))
  {
    digitalWrite(PIN_ZUMMER, HIGH);
    delay(100);
    digitalWrite(PIN_ZUMMER, LOW);
  }
  
}//END LOOP

 
  test  for define OVERSAMPLING_X1
  float  temperature=0;            // Create the temperature, pressure and altitude variables
  float  pressure=0;            // Create the temperature, pressure and altitude variables
  float  altitude=0;            // Create the temperature, pressure and altitude =vari* 
  before setup() result is:
  //power on
Start
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 0.00 temperature= 0.00 altitude= 0.00
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
LOOP
 pressure= 1008.98 temperature= 20.47 altitude= 36.12
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26
 pressure= 1008.97 temperature= 20.51 altitude= 36.26

**Comment by MartinL1** [comment]
Discussion continued here: [https://github.com/MartinL1/BMP280_DEV/issues/11](url)
